### ISSUE TITLE
Timing attack vulnerability

### ISSUE THREAD

**Issue by drbild** [iain-logan/jwt#1]
The signature comparison in vulnerable to timing attacks. You need to use a constant time comparison. See http://codahale.com/a-lesson-in-timing-attacks/ for more info.

**Comment by iain-logan** [comment]
Ah nice catch, thanks for that.

**Comment by iain-logan** [comment]
Constant time equals implemented, and now used to check signatures for equality when validating an encoded JWT. 32a64c1d144f033916277449ed381d1beb95020a
