### ISSUE TITLE
Support for RS256

### ISSUE THREAD

**Issue by maciekciolek** [iain-logan/jwt#12]
Hi,
would you be interested in PR which contains support for RS256?

**Comment by iain-logan** [comment]
Of course!
Pull requests are very welcome, as I find myself with little time these days.

**Comment by mautematico** [comment]
@maciekciolek, did you success on implementing support for RS256? :)

**Comment by jotsif** [comment]
I have an implementation working https://github.com/iain-logan/jwt/pull/14

**Comment by iain-logan** [comment]
[Pull request for RSA256 support](https://github.com/iain-logan/jwt/pull/14) accepted.
