### ISSUE TITLE
Support for scala 2.12.x

### ISSUE THREAD

**Issue by mihosang** [iain-logan/jwt#13]
This library can be used at the environment of scala 2.12.x?
When I tried to build a sample application with this lib, It can't be loaded from build.sbt file.
Is there any solution or any plan to support 2.12.x?

**Comment by iain-logan** [comment]
With cb9654a7393c9e6a390465b7bc52e16a39094269 I've added 2.12.1 support.
If you want to go ahead and use it before I do a new release, you can publish a version with these changes locally by following [these steps](http://www.scala-sbt.org/0.13/docs/Publishing.html).
