### ISSUE TITLE
Support for Scala 2.12

### ISSUE THREAD

**Issue by fdietze** [iain-logan/jwt#16]
Hi, how far is the Scala 2.12 support? How can I help?

**Comment by peterticketfly** [comment]
looks like it was committed, just not published (1.2.1) to maven central?

**Comment by kciesielski** [comment]
@iain-logan Can you publish 1.2.1? We're hoping for Scala 2.12 support too :)

**Comment by iain-logan** [comment]
I've done a version bump and published it to Maven central.

Just depend on it in the usual fashion: `libraryDependencies += "io.igl" %% "jwt" % "1.2.2"`

It's got cross Scala version support, so will work in both Scala `2.11` and `2.12`.

Apologies for the delay on this, I've not been giving this project the time it deserves. I'm getting back on top of things now, currently working on closing out some of the open issues (e.g. https://github.com/iain-logan/jwt/issues/11).
