### ISSUE TITLE
Update documentation: no need to include play-json in own build.sbt

### ISSUE THREAD

**Issue by aggenebbisj** [iain-logan/jwt#3]
> You will need to add `play-json` as a dependency to your project when using private fields. Do this by adding the below line to your `build.sbt` file.
> 
> `libraryDependencies ++= Seq("com.typesafe.play" %% "play-json" % "2.4.0")`

It seems this library is already included in your `build.sbt`:

```
libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play-json" % "2.4.0",
  "commons-codec" % "commons-codec" % "1.10",
  "org.scalatest" % "scalatest_2.11" % "2.2.4" % "test"
)
```

Nice library btw :-)

**Comment by iain-logan** [comment]
Nice catch, commit d3d0363f7512b30492b33934a3b4371f6f0a8c7f updates the README accordingly.

> Nice library btw :-)

Thank you!
