### ISSUE TITLE
decoding utf-8 claims

### ISSUE THREAD

**Issue by narerkrit-dotography** [iain-logan/jwt#5]
Hi,

The method `DecodedJwt.validateEncodedJwt` seems to handle utf-8 characters in the token incorrectly, decoding to the default character encoding instead.

I'm not sure, but I think the `private def decodeBase64` [here](https://github.com/iain-logan/jwt/blob/master/src/main/scala/io/igl/jwt/DecodedJwt.scala#L79) needs a `"UTF-8"` argument for the `new String` creation. 

It would be even nicer for other people to have an option of what character encoding to use. But just utf-8 would be nice enough for me.

Thank you :)

**Comment by iain-logan** [comment]
Hi, and apologies for my rather late response!

As of 652e67d0621c0de36c1079ff40bca7f4107f0881, calls to `validateEncodedJwt` can now be optionally provided a charset, otherwise it will default to `"UTF-8"`.

You might do something like this now:

```
DecodedJwt.validateEncodedJwt(
  jwt,
  "secret",
  Algorithm.HS256,
  Set(Typ),
  Set(Iss),
  iss = Some(Iss("readme")),
  charset = "US-ASCII"
)
```

Many thanks for bringing this to my attention :).
